# Generated by Django 4.1.4 on 2022-12-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='rides_offered',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='rides_taken',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
