# Generated by Django 4.1.4 on 2022-12-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
